### ISSUE TITLE
Question - pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by mccoydj1** [ronny-rentner/UltraDict#6] opened 2022-04-20 15:23 UTC
I got an error 
pickle.UnpicklingError: pickle data was truncated

while try to utilize this library... how does this error message get generated? and how can I avoid this in the future?

Another weird one
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 201: invalid continuation byte

**Comment by ronny-rentner** [comment] 2022-04-21 03:16
Hmm, something seems wrong with the shared memory. It's hard to tell where this is coming from without knowing more context.

Do you have a stack trace? Is is happening randomly or repeatedly?

With which parameters are you using UltraDict?

Are you using shared_lock=True?

**Comment by mccoydj1** [comment] 2022-04-22 01:45
Right now I'm using these parameters... I'm happy to try changing them though to something more safe

smd = UltraDict({}, name= 'ultra', buffer_size=10000, shared_lock=False, full_dump_size=None, auto_unlink=True, recurse=False)

The problem is that its not really repeatable (yet) ... I'm not exactly sure how it happens

**Comment by ronny-rentner** [comment] 2022-04-22 03:37
I see. One cause for such not-repeatable issues can be concurrency.

You could try to set `shared_lock=True`. This is necessary if the processes are completely independent or if they are created using the spawn method (ie. on Windows).
 
Also, once you see the error, you could try opening in a Python shell, connect to the dict and try to debug:

```
>>> from UltraDict import UltraDict
>>> smd = UltraDict(name='ultra')
>>> smd.print_status()
```

I'd love to find the root cause of this issue and make UltraDict more stable. I'm currently working on adding more tests and examples.

**Comment by mccoydj1** [comment] 2022-04-22 14:26
Okay - it failed again with this error. invalid load key, '\x00'.

Here's the status

>>> smd.print_status()
{'buffer': SharedMemory('ultra_memory', size=12288),
 'buffer_size': 12288,
 'control': SharedMemory('ultra', size=1000),
 'full_dump_counter': 0,
 'full_dump_counter_remote': 0,
 'full_dump_memory': None,
 'full_dump_memory_name_remote': '',
 'full_dump_size': None,
 'full_dump_static_size_remote': <memory at 0x00000261F217CB80>,
 'lock': <RLock(None, 0)>,
 'lock_pid_remote': 0,
 'lock_remote': 0,
 'name': 'ultra',
 'recurse': False,
 'recurse_remote': 0,
 'serializer': <module 'pickle' from 'C:\\Users\\mccoy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\pickle.py'>,
 'shared_lock': False,
 'shared_lock_remote': 0,
 'update_stream_position': 0,
 'update_stream_position_remote': 0}

**Comment by ronny-rentner** [comment] 2022-04-23 05:10
As mentioned before, try to set `shared_lock=True`

Btw, configuration is shared between several instances of an `UltraDict`, so when you set the first, creator instance to `shared_lock=True` the other connected dicts should pick it up no matter what you set there.

**Comment by mccoydj1** [comment] 2022-04-23 17:54
After you mentioned that about shared locks - I realized that I was writing to the same patch of memory in several places. I ended up making several instances of memory instead of just using only one memory.

I wasn't exactly doing this.... but I was kind of doing this (by the way - this is a fantastic way to break UltraDict)

`import multiprocessing
from UltraDict import UltraDict
import numpy as np
import random
import string
import traceback

# Define some helper functions
def P1():
    ultra = UltraDict(name='ultra5')

    while True:
        try:
            ultra['P1'] = random.random()
        except Exception as e:
            print(e)

def P2():
    ultra = UltraDict(name='ultra5')

    while True:
        try:
            chars = "".join([random.choice(string.ascii_lowercase) for i in range(8)])
            ultra['P2'] = chars
        except Exception as e:
            print(e)

if __name__ == '__main__':

    ultra = UltraDict({'P1':float(0), 'P2':''}, name='ultra5')

    p1 = multiprocessing.Process(target=P1)
    p1.start()

    p2 = multiprocessing.Process(target=P2)
    p2.start()

    while True:
        print(ultra)`


I tried it with the shared lock... still breaks but in a different way

`import multiprocessing
from UltraDict import UltraDict
import numpy as np
import random
import string
import traceback

# Define some helper functions
def P1():
    ultra = UltraDict(name='ultra6')

    while True:
        try:
            ultra['P1'] = random.random()
        except Exception as e:
            print(e)

def P2():
    ultra = UltraDict(name='ultra6')

    while True:
        try:
            chars = "".join([random.choice(string.ascii_lowercase) for i in range(8)])
            ultra['P2'] = chars
        except Exception as e:
            print(e)

if __name__ == '__main__':

    ultra = UltraDict({'P1':float(0), 'P2':''}, name='ultra6', shared_lock=True)

    p1 = multiprocessing.Process(target=P1)
    p1.start()

    p2 = multiprocessing.Process(target=P2)
    p2.start()

    while True:
        print(ultra)`

**Comment by ronny-rentner** [comment] 2022-04-24 06:29
Thanks for sharing your code. On Windows, you'll need to set shared_lock=True for sure, but there's another problem even if you set shared_lock=True. This seems to be caused when one of the two processes is in the middle of loading a full dump while the other process is so fast that it creates multiple full dumps during the same time. You can soften this issue by increasing the buffer_size. The default of 10 kb is rather small if you write a lot. Increasing it to 100 kb helps a bit on my computer (on Linux).

I'm still analyzing this issue and thinking about ways to avoid it without degrading performance.

I'll shortly release a new version including a much advanced example of auto-recovery after crashes.

**Comment by ronny-rentner** [comment] 2022-05-11 11:42
Hey, so in the dev branch, I now have a possibly working version of your example code (at least I cannot produce any errors anymore) and also another, more complex example with crash recovery from stale locks.

To your code:
On Windows, you for sure have to use `shared_lock=True`. Otherwise you have no locking at all. But even with the shared_lock, there are problems in the main branch.

These problems were mainly caused by the fact that writes are protected by the lock but not reads. Reads happen opportunistically. This is usually not an issue unless the buffers are too small. Depending on your OS and how your kernel gives time to individual processes, it could happen that reads were interrupted in the middle while multiple new full dumps were created by other processes.

If you look at your example in the dev branch, I've intentionally set the buffer to tiny 100 bytes. (Please note that Windows only allows multiples of 4096 bytes, so the smallest you can get is 4096 on Windows.) This causes a lot of full dumps to happen and it triggers the error faster.

Now the code is protected from this case, it's not an error anymore, but it will still print a warning like
`WARNING:root:Full dumps too fast full_dump_counter=120366 full_dump_counter_remote=120370. Consider increasing buffer_size.`

I still have to introduce some performance tests to ensure performance is not degraded due to the latest changes.

**Comment by mccoydj1** [comment] 2022-05-23 02:10
Sorry this has been awhile. I tried the library and it failed. Interestingly - I did set the shared_lock = True and it still gave me this error - let me know your thoughts

{'auto_unlink': False,
 'buffer': SharedMemory('bin_memory', size=12288),
 'buffer_size': 12288,
 'closed': False,
 'control': SharedMemory('bin', size=1000),
 'full_dump_counter': 0,
 'full_dump_counter_remote': 1,
 'full_dump_memory': None,
 'full_dump_memory_name_remote': 'wnsm_d9b17094',
 'full_dump_size': None,
 'full_dump_static_size_remote': <memory at 0x000001EB72283F40>,
 'lock': <RLock(None, 0)>,
 'lock_pid_remote': 0,
 'lock_remote': 0,
 'name': 'bin',
 'recurse': None,
 'recurse_remote': False,
 'serializer': <module 'pickle' from 'C:\\Users\\mccoy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\pickle.py'>,
 'shared_lock': None,
 'shared_lock_remote': False,
 'update_stream_position': 12220,
 'update_stream_position_remote': 0}

**Comment by ronny-rentner** [comment] 2022-05-23 03:05
And it fails if you run examples\mccoydj1.py?

Does it throw an exception? On my Windows VM, it works. I can keep it running the whole day.

![image](https://user-images.githubusercontent.com/4419051/169735523-051cee1c-266f-45dd-997c-acaf153faf08.png)

**Comment by ronny-rentner** [comment] 2022-05-23 03:06
PS: In your print_status() output, you have `'lock': <RLock(None, 0)>,`, so it did not pick up `shared_lock=True`.

**Comment by ronny-rentner** [comment] 2022-05-23 03:09
PPS: Please be aware that settings are stored in shared memory. If you create `name="bin"` with `shared_lock=False` in one process and do not delete/unlink it, then the next attempt using `name="bin"` will read the old settings until bin is destroyed and re-created with different settings.

**Comment by ronny-rentner** [comment] 2022-05-26 05:02
No worries, I'm closing this issue now. Thanks

**Closed by ronny-rentner** 2022-05-26 05:02 UTC
